//! Thin binary wrapper around `uniffi::uniffi_bindgen_main`.
//!
//! This exists so contributors can run `cargo run -p uniffi-bindgen -- ...`
//! from a fresh checkout without needing `cargo install uniffi-bindgen`
//! on their machine. The version of uniffi used here is pinned by the
//! workspace manifest, so bindings are always generated by the same
//! revision that the dylib was built with — a common source of weird
//! "symbol not found" errors when the two drift.
//!
//! Typical invocation after building the FFI crate:
//!
//! ```sh
//! cargo build -p unovault-ffi
//! cargo run -p uniffi-bindgen -- generate \
//!     --library target/debug/libunovault_ffi.dylib \
//!     --language swift \
//!     --out-dir swift/generated
//! ```

fn main() {
    uniffi::uniffi_bindgen_main();
}
