// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(unovault_ffiFFI)
import unovault_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_unovault_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_unovault_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Swift-visible vault handle. Wraps a `CoreVault` behind a mutex so Swift
 * can hold the object across multiple method calls. The mutex also makes
 * the object `Sync + Send`, which UniFFI requires for objects that are
 * passed around on the Swift side.
 *
 * `Debug` is implemented manually so test-code that formats
 * `Result<Arc<FfiVault>, _>` compiles without exposing internal state.
 */
public protocol FfiVaultProtocol : AnyObject {
    
    /**
     * Add a new item to the vault. Returns the new item's ID as a string.
     *
     * The vault is mutated in memory immediately; call `save()` to flush
     * the pending event queue to a chunk file on disk.
     */
    func addItem(title: String, kind: FfiItemKind, username: String?, url: String?) throws  -> String
    
    /**
     * Path of the vault bundle on disk. Useful for UI status bars.
     */
    func bundlePath() throws  -> String
    
    /**
     * Install identifier in hyphenated UUID form. Matches the chunk
     * filename suffix written by this vault handle.
     */
    func installId() throws  -> String
    
    /**
     * Number of items currently in the vault.
     */
    func itemCount() throws  -> UInt64
    
    /**
     * List every item as a metadata-only summary. No secret material
     * is returned — `has_password` / `has_totp` are booleans, not the
     * actual values.
     */
    func listItems() throws  -> [FfiItemSummary]
    
    /**
     * Flush the pending event queue to a chunk file. No-op if empty.
     */
    func save() throws 
    
    /**
     * Set the notes field. Notes are not considered secret material but
     * the API still goes through the same event log to keep the LWW
     * merge path consistent.
     */
    func setNotes(itemId: String, notes: String) throws  -> Bool
    
    /**
     * Set the password field on an existing item.
     *
     * NOTE: plaintext crosses the FFI boundary as a String. That is
     * acceptable from the Swift host process (UniFFI is in-process, not
     * remote) but it IS a departure from the WebView-side rule that
     * says "UI never sees plaintext." The Swift layer between UniFFI
     * and the WebView must never forward this string into JavaScript.
     * A future iteration will replace this with a callback-based
     * "input password" flow that obtains the plaintext from a native
     * overlay and drops it immediately.
     */
    func setPassword(itemId: String, password: String) throws  -> Bool
    
}

/**
 * Swift-visible vault handle. Wraps a `CoreVault` behind a mutex so Swift
 * can hold the object across multiple method calls. The mutex also makes
 * the object `Sync + Send`, which UniFFI requires for objects that are
 * passed around on the Swift side.
 *
 * `Debug` is implemented manually so test-code that formats
 * `Result<Arc<FfiVault>, _>` compiles without exposing internal state.
 */
open class FfiVault:
    FfiVaultProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_unovault_ffi_fn_clone_ffivault(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_unovault_ffi_fn_free_ffivault(pointer, $0) }
    }

    
    /**
     * Create a brand-new vault at `bundle_path` with the given master
     * password. Returns a handle the caller uses for subsequent ops.
     *
     * `install_id_dir` is the directory where the v0 install-id store
     * persists its UUID (one file inside the directory). Swift should
     * pass `~/Library/Application Support/unovault` or similar.
     */
public static func create(bundlePath: String, password: String, installIdDir: String)throws  -> FfiVault {
    return try  FfiConverterTypeFfiVault.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_constructor_ffivault_create(
        FfiConverterString.lower(bundlePath),
        FfiConverterString.lower(password),
        FfiConverterString.lower(installIdDir),$0
    )
})
}
    
    /**
     * Unlock an existing vault. Slow — argon2id derivation is the
     * dominating cost, typically 500ms–1.5s depending on hardware.
     * Swift must call this off the main thread to avoid beachballing.
     */
public static func unlock(bundlePath: String, password: String, installIdDir: String)throws  -> FfiVault {
    return try  FfiConverterTypeFfiVault.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_constructor_ffivault_unlock(
        FfiConverterString.lower(bundlePath),
        FfiConverterString.lower(password),
        FfiConverterString.lower(installIdDir),$0
    )
})
}
    

    
    /**
     * Add a new item to the vault. Returns the new item's ID as a string.
     *
     * The vault is mutated in memory immediately; call `save()` to flush
     * the pending event queue to a chunk file on disk.
     */
open func addItem(title: String, kind: FfiItemKind, username: String?, url: String?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_add_item(self.uniffiClonePointer(),
        FfiConverterString.lower(title),
        FfiConverterTypeFfiItemKind.lower(kind),
        FfiConverterOptionString.lower(username),
        FfiConverterOptionString.lower(url),$0
    )
})
}
    
    /**
     * Path of the vault bundle on disk. Useful for UI status bars.
     */
open func bundlePath()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_bundle_path(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Install identifier in hyphenated UUID form. Matches the chunk
     * filename suffix written by this vault handle.
     */
open func installId()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_install_id(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Number of items currently in the vault.
     */
open func itemCount()throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_item_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * List every item as a metadata-only summary. No secret material
     * is returned — `has_password` / `has_totp` are booleans, not the
     * actual values.
     */
open func listItems()throws  -> [FfiItemSummary] {
    return try  FfiConverterSequenceTypeFfiItemSummary.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_list_items(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Flush the pending event queue to a chunk file. No-op if empty.
     */
open func save()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_save(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Set the notes field. Notes are not considered secret material but
     * the API still goes through the same event log to keep the LWW
     * merge path consistent.
     */
open func setNotes(itemId: String, notes: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_set_notes(self.uniffiClonePointer(),
        FfiConverterString.lower(itemId),
        FfiConverterString.lower(notes),$0
    )
})
}
    
    /**
     * Set the password field on an existing item.
     *
     * NOTE: plaintext crosses the FFI boundary as a String. That is
     * acceptable from the Swift host process (UniFFI is in-process, not
     * remote) but it IS a departure from the WebView-side rule that
     * says "UI never sees plaintext." The Swift layer between UniFFI
     * and the WebView must never forward this string into JavaScript.
     * A future iteration will replace this with a callback-based
     * "input password" flow that obtains the plaintext from a native
     * overlay and drops it immediately.
     */
open func setPassword(itemId: String, password: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_unovault_ffi_fn_method_ffivault_set_password(self.uniffiClonePointer(),
        FfiConverterString.lower(itemId),
        FfiConverterString.lower(password),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiVault: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiVault

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiVault {
        return FfiVault(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiVault) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiVault {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiVault, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVault_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiVault {
    return try FfiConverterTypeFfiVault.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVault_lower(_ value: FfiVault) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiVault.lower(value)
}


/**
 * Item summary exposed to Swift. No secret material — callers use a
 * separate (future) API to request copy/reveal for a specific field.
 */
public struct FfiItemSummary {
    /**
     * Stable item identifier as a hyphenated UUID string. Swift keeps
     * this opaque and passes it back to Rust for further operations.
     */
    public var id: String
    public var title: String
    public var kind: FfiItemKind
    public var username: String?
    public var url: String?
    public var hasPassword: Bool
    public var hasTotp: Bool
    public var createdAtMs: UInt64
    public var modifiedAtMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable item identifier as a hyphenated UUID string. Swift keeps
         * this opaque and passes it back to Rust for further operations.
         */id: String, title: String, kind: FfiItemKind, username: String?, url: String?, hasPassword: Bool, hasTotp: Bool, createdAtMs: UInt64, modifiedAtMs: UInt64) {
        self.id = id
        self.title = title
        self.kind = kind
        self.username = username
        self.url = url
        self.hasPassword = hasPassword
        self.hasTotp = hasTotp
        self.createdAtMs = createdAtMs
        self.modifiedAtMs = modifiedAtMs
    }
}



extension FfiItemSummary: Equatable, Hashable {
    public static func ==(lhs: FfiItemSummary, rhs: FfiItemSummary) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.url != rhs.url {
            return false
        }
        if lhs.hasPassword != rhs.hasPassword {
            return false
        }
        if lhs.hasTotp != rhs.hasTotp {
            return false
        }
        if lhs.createdAtMs != rhs.createdAtMs {
            return false
        }
        if lhs.modifiedAtMs != rhs.modifiedAtMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(kind)
        hasher.combine(username)
        hasher.combine(url)
        hasher.combine(hasPassword)
        hasher.combine(hasTotp)
        hasher.combine(createdAtMs)
        hasher.combine(modifiedAtMs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiItemSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiItemSummary {
        return
            try FfiItemSummary(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeFfiItemKind.read(from: &buf), 
                username: FfiConverterOptionString.read(from: &buf), 
                url: FfiConverterOptionString.read(from: &buf), 
                hasPassword: FfiConverterBool.read(from: &buf), 
                hasTotp: FfiConverterBool.read(from: &buf), 
                createdAtMs: FfiConverterUInt64.read(from: &buf), 
                modifiedAtMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiItemSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterTypeFfiItemKind.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.url, into: &buf)
        FfiConverterBool.write(value.hasPassword, into: &buf)
        FfiConverterBool.write(value.hasTotp, into: &buf)
        FfiConverterUInt64.write(value.createdAtMs, into: &buf)
        FfiConverterUInt64.write(value.modifiedAtMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemSummary_lift(_ buf: RustBuffer) throws -> FfiItemSummary {
    return try FfiConverterTypeFfiItemSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemSummary_lower(_ value: FfiItemSummary) -> RustBuffer {
    return FfiConverterTypeFfiItemSummary.lower(value)
}


/**
 * Flat error enum exposed to Swift. The 5-category `VaultError` taxonomy
 * collapses to this shape because UniFFI renders nested enums less
 * ergonomically in Swift than a flat category-tagged enum.
 *
 * Swift code should pattern-match on the variant and show the
 * category-appropriate headline from its own copy tables — the `message`
 * field is log text, not UI copy.
 */
public enum FfiError {

    
    
    /**
     * Something the user can fix by retrying with different input.
     */
    case UserActionable(message: String
    )
    /**
     * Temporary environmental failure. Retry later.
     */
    case NetworkTransient(message: String
    )
    /**
     * Device hardware state prevents the operation.
     */
    case HardwareIssue(message: String
    )
    /**
     * A bug inside unovault. The user should see "copy diagnostics".
     */
    case BugInUnovault(message: String
    )
    /**
     * The OS sandbox or permission system refused the operation.
     */
    case PlatformPolicy(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UserActionable(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NetworkTransient(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .HardwareIssue(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .BugInUnovault(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .PlatformPolicy(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .UserActionable(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .NetworkTransient(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .HardwareIssue(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .BugInUnovault(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .PlatformPolicy(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Kind of a vault item. Mirrors `unovault_core::event::ItemKind` but as
 * a UniFFI-compatible enum (no `#[non_exhaustive]`; UniFFI needs full
 * enumeration at binding time).
 */

public enum FfiItemKind {
    
    case password
    case passkey
    case totp
    case sshKey
    case apiToken
    case secureNote
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiItemKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiItemKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiItemKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .password
        
        case 2: return .passkey
        
        case 3: return .totp
        
        case 4: return .sshKey
        
        case 5: return .apiToken
        
        case 6: return .secureNote
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiItemKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .password:
            writeInt(&buf, Int32(1))
        
        
        case .passkey:
            writeInt(&buf, Int32(2))
        
        
        case .totp:
            writeInt(&buf, Int32(3))
        
        
        case .sshKey:
            writeInt(&buf, Int32(4))
        
        
        case .apiToken:
            writeInt(&buf, Int32(5))
        
        
        case .secureNote:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemKind_lift(_ buf: RustBuffer) throws -> FfiItemKind {
    return try FfiConverterTypeFfiItemKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemKind_lower(_ value: FfiItemKind) -> RustBuffer {
    return FfiConverterTypeFfiItemKind.lower(value)
}



extension FfiItemKind: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiItemSummary: FfiConverterRustBuffer {
    typealias SwiftType = [FfiItemSummary]

    public static func write(_ value: [FfiItemSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiItemSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiItemSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiItemSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiItemSummary.read(from: &buf))
        }
        return seq
    }
}
/**
 * Semantic version of the `unovault-ffi` crate. Exposed so Swift can log
 * the bridge version separately from the app version.
 */
public func ffiVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unovault_ffi_fn_func_ffi_version($0
    )
})
}
/**
 * Semantic version of the `.unovault` on-disk format this bridge speaks.
 * Swift UI should display this in a diagnostics view.
 */
public func formatVersion() -> UInt16 {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_unovault_ffi_fn_func_format_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_unovault_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_unovault_ffi_checksum_func_ffi_version() != 47163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_func_format_version() != 9553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_add_item() != 53813) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_bundle_path() != 5919) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_install_id() != 33483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_item_count() != 61163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_list_items() != 15510) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_save() != 32145) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_set_notes() != 60300) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_method_ffivault_set_password() != 32027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_constructor_ffivault_create() != 25223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unovault_ffi_checksum_constructor_ffivault_unlock() != 65029) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all