// swift-tools-version:5.9
//
// UnovaultFFI — Swift bindings to the Rust vault engine.
//
// This package wraps the uniffi-generated Swift code + the `libunovault_ffi.dylib`
// built by `cargo build -p unovault-ffi`. It is intentionally minimal:
//
//   * `UnovaultFFIC` is a system library target that imports the C header
//     + modulemap generated by uniffi. The Swift wrapper target imports this
//     module to access the raw FFI symbols.
//
//   * `UnovaultFFI` is the Swift target. It contains the uniffi-generated
//     `UnovaultFFI.swift` file (copied from `swift/generated/` by the
//     `scripts/update-swift-bindings.sh` step) and nothing else.
//
//   * Tests link against the same dylib via `unsafeFlags`, pointing at the
//     debug build output under `../../target/debug`. For a packaged
//     distribution (week 5-9 when the Tauri app shell lands) the dylib
//     will be bundled into a `.xcframework` and the unsafeFlags disappear.
//
// Usage from the repo root:
//
//     cargo build -p unovault-ffi
//     cd swift/UnovaultFFI
//     swift test
//
// The smoke-test target proves that the Rust → Swift → Rust round-trip
// through UniFFI actually works: create vault, add item, save, reopen,
// verify. If this test passes, the Week 5-6 bridge gate is satisfied.

import PackageDescription

let package = Package(
    name: "UnovaultFFI",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .library(
            name: "UnovaultFFI",
            targets: ["UnovaultFFI"]
        ),
    ],
    targets: [
        // C header + modulemap describing the Rust cdylib's ABI.
        .target(
            name: "UnovaultFFIC",
            path: "Sources/UnovaultFFIC",
            publicHeadersPath: "."
        ),

        // The Swift wrapper. Depends on the C module so it can call the
        // raw extern "C" functions, and linker-flags the debug dylib so
        // the resulting binary can actually find the symbols at runtime.
        .target(
            name: "UnovaultFFI",
            dependencies: ["UnovaultFFIC"],
            path: "Sources/UnovaultFFI",
            linkerSettings: [
                .unsafeFlags([
                    "-L../../target/debug",
                    "-lunovault_ffi",
                    "-Xlinker", "-rpath",
                    "-Xlinker", "@executable_path/../../../../target/debug",
                ]),
            ]
        ),

        .testTarget(
            name: "UnovaultFFITests",
            dependencies: ["UnovaultFFI"],
            path: "Tests/UnovaultFFITests"
        ),
    ]
)
